# -*- coding: utf-8 -*-
"""轻量极速版_v23.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NX-JAaUa5lIM8dbnB5n6KotrkA36a4cy
"""

import os
import re
import shutil
import warnings
import pandas as pd
import fitz  # PyMuPDF，极速 PDF 解析底层引擎
from rapidocr_onnxruntime import RapidOCR # 轻量化 AI 视觉 OCR 模型

# 屏蔽 openpyxl 读取 Excel 打印区域时的无害警告，让界面更清爽
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

# ============================================================
# 【AI OCR 引擎初始化】
# ============================================================
try:
    ocr_engine = RapidOCR()
    USE_OCR = True
    ocr_status_msg = "✅ RapidOCR (ONNX极速版) 已激活"
except Exception as e:
    USE_OCR = False
    ocr_status_msg = f"❌ RapidOCR 初始化失败: {e}"

# ============================================================
# 校准证书智能重命名与归档工具 v23.0 (轻量极速版)
# 核心架构升级：PyMuPDF + RapidOCR，10倍提速，极低 CPU/内存占用
# ============================================================

VERSION = "v23.0"

print("=" * 70)
print(f"  校准证书智能重命名与归档工具 {VERSION}")
print("  支持机构：帝恩 / 达丰 / 中广测 / 深圳计量院 / 中检(深圳)")
print(f"  AI 视觉引擎：{ocr_status_msg}")
print("=" * 70)

# ==========================================
# 第一步：加载两份台账 (构建全局天眼词库)
# ==========================================

dn_mapping = {}
dn_valid_assets = []
DN_EXCEL   = '2026年各实验室仪器设备校准清单.xlsx'
DN_SHEET   = '  2026年度仪器检定校准计划总表'

if os.path.exists(DN_EXCEL):
    print(f"\n✅ 检测到帝恩台账：{DN_EXCEL}")
    try:
        df_dn = pd.read_excel(DN_EXCEL, sheet_name=DN_SHEET, header=1)
        df_dn.columns = df_dn.columns.str.strip().str.replace('\n','').str.replace('\r','')
        for col in ['设备编号', '实验室名称', '设备名称']:
            if col in df_dn.columns:
                df_dn[col] = df_dn[col].astype(str).str.strip()
        for _, row in df_dn.iterrows():
            if '设备编号' in row:
                dn_mapping[row['设备编号']] = {
                    'lab': row.get('实验室名称', '未知实验室'),
                    'inst': row.get('设备名称', None)
                }
        invalid = {'nan','None','','/','\\','-','无','无编号'}
        dn_valid_assets = sorted(
            [k for k in dn_mapping if k not in invalid],
            key=len, reverse=True
        )
        print(f"   帝恩台账加载完成，共 {len(dn_valid_assets)} 条有效编号。")
    except Exception as e:
        print(f"⚠️  帝恩台账加载失败：{e}")
else:
    print(f"\n⚠️  未找到帝恩台账【{DN_EXCEL}】，帝恩证书将跳过台账匹配。")

group_mapping = {}
trace_valid_assets = []
TRACE_EXCEL = '2026年年度计划汇总.xlsx'
TRACE_SHEET = '2026年量值溯源总表'

if os.path.exists(TRACE_EXCEL):
    print(f"\n✅ 检测到量值溯源台账：{TRACE_EXCEL}")
    try:
        df_raw = pd.read_excel(TRACE_EXCEL, sheet_name=TRACE_SHEET, header=None)
        header_row = 0
        for idx, row in df_raw.iterrows():
            row_str = ' '.join(str(v) for v in row.values)
            if '设备编号' in row_str and '所属组' in row_str:
                header_row = idx
                break

        df_trace = pd.read_excel(TRACE_EXCEL, sheet_name=TRACE_SHEET, header=header_row)
        df_trace.columns = df_trace.columns.str.strip().str.replace('\n','').str.replace('\r','')

        no_col = next((c for c in df_trace.columns if re.search(r'设备编号|器具编号|资产编号|管理号', c)), None)
        grp_col = next((c for c in df_trace.columns if re.search(r'所属组|组别|实验室组', c)), None)
        inst_col = next((c for c in df_trace.columns if re.search(r'设备名称|仪器名称|器具名称', c)), None)

        if no_col:
            df_trace[no_col]  = df_trace[no_col].astype(str).str.strip()
            if grp_col: df_trace[grp_col] = df_trace[grp_col].astype(str).str.strip()
            if inst_col: df_trace[inst_col] = df_trace[inst_col].astype(str).str.strip()

            invalid_g = {'nan','None','','/','—','无'}
            for _, row in df_trace.iterrows():
                code = row[no_col]
                grp  = row[grp_col] if grp_col else '未知组别'
                inst = row[inst_col] if inst_col else None
                if code not in invalid_g:
                    trace_valid_assets.append(code)
                    group_mapping[code] = {
                        'group': grp if grp not in invalid_g else '未知组别',
                        'inst': inst if inst not in invalid_g else None
                    }
            print(f"   量值溯源台账加载完成，共 {len(trace_valid_assets)} 条编号与组别映射。")
        else:
            print(f"⚠️  量值溯源台账未找到编号列，跳过加载。")
    except Exception as e:
        print(f"⚠️  量值溯源台账加载失败：{e}")
else:
    print(f"\n⚠️  未找到量值溯源台账【{TRACE_EXCEL}】，将降级使用正则抓取。")

all_valid_assets = sorted(list(set(dn_valid_assets + trace_valid_assets)), key=len, reverse=True)

extracted_info_list = []

# ==========================================
# 第二步：通用工具函数
# ==========================================

def sanitize_filename(text):
    if not text: return "未查找到"
    cleaned = re.sub(r'[\\/*?:"<>|]', '-', str(text)).strip()
    return cleaned if cleaned else "未查找到"

def clean_date_chinese(date_str):
    if not date_str: return None
    return re.sub(r'[年月日\s]', '', date_str)

def clean_date_hyphen(date_str):
    if not date_str: return None
    return date_str.replace('-', '').strip()

def find_value_by_keyword(text, keyword_pattern, value_pattern, search_range=4, col_tolerance_left=15, col_tolerance_right=60):
    lines = text.split('\n')
    for i, line in enumerate(lines):
        kw_match = re.search(keyword_pattern, line, re.IGNORECASE)
        if not kw_match: continue
        col_idx = kw_match.start()
        end_idx = kw_match.end()
        for j in range(i, min(i + search_range, len(lines))):
            target_line = lines[j]
            for val_match in re.finditer(value_pattern, target_line):
                v_start = val_match.start()
                val = val_match.group(0).strip()
                if not val: continue
                if j == i:
                    if v_start >= end_idx: return val
                else:
                    if (col_idx - col_tolerance_left) <= v_start <= (col_idx + col_tolerance_right):
                        return val
    return None

def extract_robust_date(text_clean_fixed, text_fixed, keyword_pattern_clean, keyword_pattern_raw):
    match = re.search(keyword_pattern_clean, text_clean_fixed, re.IGNORECASE)
    if match:
        start = max(0, match.start() - 80)
        end = min(len(text_clean_fixed), match.end() + 150)
        window = text_clean_fixed[start:end]
        dates = re.findall(r'\d{4}[-\.年/]\d{1,2}[-\.月/]\d{1,2}日?', window)
        if dates:
            return re.sub(r'[^\d]', '', dates[0])[:8]

    for match in re.finditer(keyword_pattern_raw, text_fixed, re.IGNORECASE):
        start = max(0, match.start() - 100)
        end = min(len(text_fixed), match.end() + 250)
        window = text_fixed[start:end]
        dates = re.findall(r'\d{4}\s*[-\.年/]\s*\d{1,2}\s*[-\.月/]\s*\d{1,2}\s*日?', window)
        if dates:
            return re.sub(r'[^\d]', '', dates[0])[:8]
    return None

def filter_asset_no(asset_no):
    if not asset_no or asset_no in ('未知编号', '未识别到编号'): return '未识别到编号'
    asset_no = asset_no.upper()

    asset_no = re.sub(r'(SERIALNO|ASSETNO|SERIAL|ASSET|MODEL|TYPE|NO|NAME)$', '', asset_no, flags=re.IGNORECASE)
    asset_no = re.sub(r'^WI(\d+)', r'WJ\1', asset_no)
    asset_no = re.sub(r'^HO(\d+)', r'H0\1', asset_no)
    asset_no = re.sub(r'^BES40(\d+)', r'H0\1', asset_no)
    asset_no = re.sub(r'^(DAFD|DAF|DAP|D)(H\d+|WSJ\d+|NDJ\d+|WJ\d+|A\d+|B\d+)', r'\2', asset_no)

    if not asset_no: return '未识别到编号'
    if re.match(r'^(JJF|JJG|GB|YY|JB|JC|SJ|T|SN|MT|PALL|ABSCIEX|WATERS|THERMO|AGILENT|SHIMADZU|DAF|ASSET|DATE|SERIAL|MODEL|DESCRIPTION|INFORMATION|CERTIFICATE|PAGE|EQUIPMENT)\b', asset_no):
        return '未识别到编号'
    if re.match(r'^L\d{4}$', asset_no):
        return '未识别到编号'

    return asset_no.replace('/', '-')

# ==========================================
# 全局统一正则模式
# ==========================================
INST_PATTERN = r'[\u4e00-\u9fa5A-Za-z][A-Za-z0-9\-\u4e00-\u9fa5\(\)（）/ \.]{1,35}'
ASSET_PATTERN = r'[A-Za-z]{1,6}[0-9]{1,10}[A-Za-z0-9\-/]*'

def extract_robust_asset(text_fixed, text_clean_fixed, keyword_pattern, keyword_pattern_clean, exclude_str=None):
    best_asset = '未识别到编号'
    min_dist = 999999
    exclude_str = exclude_str.upper() if exclude_str else None

    for kw_match in re.finditer(keyword_pattern_clean, text_clean_fixed, re.IGNORECASE):
        kw_center = (kw_match.start() + kw_match.end()) // 2
        start = max(0, kw_match.start() - 200)
        end = min(len(text_clean_fixed), kw_match.end() + 300)
        window = text_clean_fixed[start:end]

        for p_match in re.finditer(ASSET_PATTERN, window):
            p = p_match.group(0)
            if len(p) >= 4:
                filtered = filter_asset_no(p)
                if filtered != '未识别到编号':
                    if exclude_str and (filtered == exclude_str or filtered in exclude_str):
                        continue

                    p_center = start + p_match.start() + len(p)//2
                    dist = abs(p_center - kw_center)
                    if re.match(r'^(H|WSJ|NDJ|WJ|A|B)\d+', filtered, re.IGNORECASE):
                        dist -= 10000
                    if dist < min_dist:
                        min_dist = dist
                        best_asset = filtered

    for kw_match in re.finditer(keyword_pattern, text_fixed, re.IGNORECASE):
        kw_center = (kw_match.start() + kw_match.end()) // 2
        start = max(0, kw_match.start() - 200)
        end = min(len(text_fixed), kw_match.end() + 300)
        window = text_fixed[start:end]

        for p_match in re.finditer(ASSET_PATTERN, window):
            p = p_match.group(0)
            if len(p) >= 4:
                filtered = filter_asset_no(p)
                if filtered != '未识别到编号':
                    if exclude_str and (filtered == exclude_str or filtered in exclude_str):
                        continue

                    p_center = start + p_match.start() + len(p)//2
                    dist = abs(p_center - kw_center)
                    if re.match(r'^(H|WSJ|NDJ|WJ|A|B)\d+', filtered, re.IGNORECASE):
                        dist -= 10000
                    if dist < min_dist:
                        min_dist = dist
                        best_asset = filtered
    return best_asset

def extract_robust_inst_name(text_fixed, keyword_pattern):
    lines = [line.strip() for line in text_fixed.split('\n') if line.strip()]
    for i, line in enumerate(lines):
        kw_match = re.search(keyword_pattern, line, re.IGNORECASE)
        if kw_match:
            prefix = line[:kw_match.start()].strip()
            prefix = re.sub(r'Description|DAF|DAP|[\u4e00-\u9fa5]+(?:市|区|街道|社区|路|栋|楼|村|镇|实验室|FQT|中心)[\u4e00-\u9fa5A-Za-z0-9\-#]*', ' ', prefix, flags=re.IGNORECASE).strip()
            if prefix and len(prefix.replace(' ', '')) >= 2 and re.match(r'^' + INST_PATTERN + r'$', prefix):
                if not re.match(r'^(Description|Model|Type|DAF|DAP|Asset|No|Serial|MAC|MAA|MRA|CNAS|ILAC|Client|委托方|Information|Certificate|Page|Pages|Equipment|Name|Address)$', prefix.replace(' ', ''), re.IGNORECASE):
                    return prefix

            for j in range(1, 9):
                if i - j >= 0:
                    val = lines[i - j]
                    val = re.sub(r'Description|DAF|DAP|[\u4e00-\u9fa5]+(?:市|区|街道|社区|路|栋|楼|村|镇|实验室|FQT|中心)[\u4e00-\u9fa5A-Za-z0-9\-#]*', ' ', val, flags=re.IGNORECASE).strip()
                    if val and len(val.replace(' ', '')) >= 2 and re.match(r'^' + INST_PATTERN + r'$', val):
                        if not re.match(r'^(Description|Model|Type|DAF|DAP|Asset|No|Serial|MAC|MAA|MRA|CNAS|ILAC|Client|委托方|Information|Certificate|Page|Pages|Equipment|Name|Address)$', val.replace(' ', ''), re.IGNORECASE):
                            return val
    return '未查找到'

def lookup_group(code):
    if not code or code in ('未知编号', '未识别到编号'): return '未知组别'
    code_upper = code.upper()
    for k, v in group_mapping.items():
        if k.upper() == code_upper: return v['group']
    return '未知组别'

def lookup_inst(code):
    if not code or code in ('未知编号', '未识别到编号'): return None
    code_upper = code.upper()
    for k, v in group_mapping.items():
        if k.upper() == code_upper and v.get('inst') and str(v['inst']).lower() not in ('nan', 'none', ''):
            return v['inst']
    for k, v in dn_mapping.items():
        if k.upper() == code_upper and v.get('inst') and str(v['inst']).lower() not in ('nan', 'none', ''):
            return v['inst']
    return None

def auto_match_from_registry(text_fixed, text_clean_fixed):
    asset_no = '未识别到编号'
    for asset in all_valid_assets:
        if len(asset) < 3: continue
        if re.match(r'^[A-Za-z]+\d+', asset) or len(asset) >= 4:
            if asset in text_fixed or asset in text_clean_fixed:
                asset_no = asset
                break

    inst_name = lookup_inst(asset_no)
    return asset_no, inst_name

# ==========================================
# 第三步：机构识别
# ==========================================

def identify_issuer(text_clean):
    text_lower = text_clean.lower()
    if re.search(r'帝恩|dntesting|donggauandn|dn260|cnasl6483', text_lower): return 'DN'
    if re.search(r'达丰|dafmetrology|shenzhendaf|dafdjax|cnasl6592', text_lower): return 'DAF'
    if re.search(r'深圳市计量质量检测研究院|smq\.com\.cn|cnasl0579|jl\d{10}', text_lower): return 'SMQ'
    if re.search(r'中广测|广州中广测|guangzhounem|gznem|tic2600|cnasl7613|gznem\.com', text_lower): return 'NEM'
    if re.search(r'中检|ccic|中国检验认证集团|cnasl3103|计量测试服务', text_lower): return 'CCIC'
    return 'UNKNOWN'

# ==========================================
# 第四步：各机构专属提取器
# ==========================================

def extract_dn(text, text_clean):
    text_fixed = re.sub(r'\b(DAF|DAP)\b', ' ', text, flags=re.IGNORECASE)
    text_fixed = re.sub(r'NobJo|NnopbJo|NOPBJO', 'NDJ0', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'HO(\d+)', r'H0\1', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'WI(\d+)', r'WJ\1', text_fixed, flags=re.IGNORECASE)
    text_clean_fixed = text_fixed.replace(' ', '').replace('\n', '')

    serial_match = re.search(r'(?:出厂编号|Serial\s*No\.?)\s*[:：]?\s*([A-Za-z0-9\-/]{4,})', text_fixed, re.IGNORECASE)
    serial_no_str = serial_match.group(1) if serial_match else None

    asset_no, inst_name = auto_match_from_registry(text_fixed, text_clean_fixed)

    if asset_no == '未识别到编号':
        asset_no = extract_robust_asset(text_fixed, text_clean_fixed, r'管\s*理\s*号|Asset\s*No\.?', r'管理号|AssetNo\.?', exclude_str=serial_no_str)
        if asset_no != '未识别到编号' and not inst_name:
            inst_name = lookup_inst(asset_no)

    info = dn_mapping.get(asset_no, {})
    lab_name  = info.get('lab', '未查找到')
    if not inst_name:
        inst_name = extract_robust_inst_name(text_fixed, r'仪\s*器\s*名\s*称|Description')
        if inst_name == '未查找到':
            inst_name = info.get('inst') or find_value_by_keyword(text_fixed, r'仪\s*器\s*名\s*称|Description', INST_PATTERN, col_tolerance_right=60) or '未查找到'

    cal_date = extract_robust_date(text_clean_fixed, text_fixed, r'校准日期|DateofCalibration', r'校\s*准\s*日\s*期|Date\s*of\s*Calibration') or '未知校准'
    issue_date = extract_robust_date(text_clean_fixed, text_fixed, r'签发日期|DateofIssue', r'签\s*发\s*日\s*期|Date\s*of\s*Issue') or '未知签发'
    return {'asset_no': asset_no, 'inst_name': inst_name, 'lab_name': lab_name, 'cal_date': cal_date, 'issue_date': issue_date}

def extract_daf(text, text_clean):
    text_fixed = re.sub(r'\b(DAF|DAP)\b', ' ', text, flags=re.IGNORECASE)
    text_fixed = re.sub(r'NobJo|NnopbJo|NOPBJO', 'NDJ0', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'HO(\d+)', r'H0\1', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'WI(\d+)', r'WJ\1', text_fixed, flags=re.IGNORECASE)
    text_clean_fixed = text_fixed.replace(' ', '').replace('\n', '')

    serial_match = re.search(r'(?:出厂编号|Serial\s*No\.?)\s*[:：]?\s*([A-Za-z0-9\-/]{4,})', text_fixed, re.IGNORECASE)
    serial_no_str = serial_match.group(1) if serial_match else None

    asset_no, inst_name = auto_match_from_registry(text_fixed, text_clean_fixed)

    if asset_no == '未识别到编号':
        asset_no = extract_robust_asset(text_fixed, text_clean_fixed, r'管\s*理\s*号|Asset\s*No\.?', r'管理号|AssetNo\.?', exclude_str=serial_no_str)
        if asset_no != '未识别到编号' and not inst_name:
            inst_name = lookup_inst(asset_no)

    if not inst_name:
        inst_name = extract_robust_inst_name(text_fixed, r'仪\s*器\s*名\s*称|Description')

        if inst_name == '未查找到':
            block_match = re.search(r'仪\s*器\s*名\s*称(.*?)(?:型号规格|Model|制造厂商)', text_fixed, re.IGNORECASE | re.DOTALL)
            if block_match:
                block = block_match.group(1)
                block = re.sub(r'Description|DAF|DAP|[\u4e00-\u9fa5]+(?:市|区|街道|社区|路|栋|楼|村|镇|实验室|FQT|中心)[\u4e00-\u9fa5A-Za-z0-9\-#]*', ' ', block, flags=re.IGNORECASE)
                for w in block.split():
                    w = w.strip()
                    if len(w) >= 2 and re.match(r'^' + INST_PATTERN + r'$', w) and not re.match(r'^(Description|Model|Type|DAF|DAP|Asset|No|Serial|MAC|MAA|MRA|CNAS|ILAC|Information|Certificate|Page|Pages|Equipment|Name)$', w.replace(' ',''), re.IGNORECASE):
                        inst_name = w
                        break

        if inst_name == '未查找到':
            inst_name_match = find_value_by_keyword(text_fixed, r'仪\s*器\s*名\s*称|Description', INST_PATTERN, search_range=10, col_tolerance_right=100)
            if inst_name_match and not re.search(r'市|区|街道|路|楼|社区|型号规格|MAC|MAA|MRA|CNAS|Information|Certificate', inst_name_match, re.IGNORECASE):
                inst_name = inst_name_match

    cal_date = extract_robust_date(text_clean_fixed, text_fixed, r'校准日期|DateofCalibration', r'校\s*准\s*日\s*期|Date\s*of\s*Calibration') or '未知校准'

    return {'asset_no': asset_no, 'inst_name': inst_name, 'cal_date': cal_date, 'group': lookup_group(asset_no)}

def extract_nem(text, text_clean):
    text_fixed = re.sub(r'\b(DAF|DAP)\b', ' ', text, flags=re.IGNORECASE)
    text_fixed = re.sub(r'NobJo|NnopbJo|NOPBJO', 'NDJ0', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'HO(\d+)', r'H0\1', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'WI(\d+)', r'WJ\1', text_fixed, flags=re.IGNORECASE)
    text_clean_fixed = text_fixed.replace(' ', '').replace('\n', '')

    serial_match = re.search(r'(?:出厂编号|Serial\s*No\.?)\s*[:：]?\s*([A-Za-z0-9\-/]{4,})', text_fixed, re.IGNORECASE)
    serial_no_str = serial_match.group(1) if serial_match else None

    asset_no, inst_name = auto_match_from_registry(text_fixed, text_clean_fixed)

    if asset_no == '未识别到编号':
        asset_no = extract_robust_asset(text_fixed, text_clean_fixed, r'器\s*具\s*编\s*号|Serial\s*[N№]', r'器具编号|Serial[N№]', exclude_str=serial_no_str)
        if asset_no != '未识别到编号' and not inst_name:
            inst_name = lookup_inst(asset_no)

    if not inst_name:
        inst_name = extract_robust_inst_name(text_fixed, r'器\s*具\s*名\s*称|Description')

        if inst_name == '未查找到':
            inst_name_match = find_value_by_keyword(text_fixed, r'器\s*具\s*名\s*称|Description', INST_PATTERN, search_range=10, col_tolerance_right=80)
            if inst_name_match and not re.search(r'市|区|街道|路|楼|社区|MAC|MAA|MRA|CNAS|Information|Certificate', inst_name_match, re.IGNORECASE):
                inst_name = inst_name_match
            else:
                for match in re.finditer(r'(?:器\s*具\s*名\s*称|Description).{0,150}?(' + INST_PATTERN + r')', text_fixed, re.IGNORECASE | re.DOTALL):
                    val = match.group(1).strip()
                    if val and not re.search(r'市|区|街道|路|楼|社区|型号规格|制造厂商|出厂编号|器具编号|联络信息|委托方|MAC|MAA|MRA|Information|Certificate', val, re.IGNORECASE):
                        inst_name = val
                        break

    cal_date = extract_robust_date(text_clean_fixed, text_fixed, r'校准日期|DateofCalibrat(?:e|ion)', r'校\s*准\s*日\s*期|Date\s*of\s*Calibrat(?:e|ion)') or '未知校准'

    return {'serial_no': asset_no, 'inst_name': inst_name, 'cal_date': cal_date, 'group': lookup_group(asset_no)}

def extract_smq(text, text_clean):
    text_fixed = re.sub(r'\b(DAF|DAP)\b', ' ', text, flags=re.IGNORECASE)
    text_fixed = re.sub(r'NobJo|NnopbJo|NOPBJO', 'NDJ0', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'HO(\d+)', r'H0\1', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'WI(\d+)', r'WJ\1', text_fixed, flags=re.IGNORECASE)
    text_clean_fixed = text_fixed.replace(' ', '').replace('\n', '')

    serial_match = re.search(r'(?:出厂编号|Serial\s*No\.?)\s*[:：]?\s*([A-Za-z0-9\-/]{4,})', text_fixed, re.IGNORECASE)
    serial_no_str = serial_match.group(1) if serial_match else None

    asset_no, inst_name = auto_match_from_registry(text_fixed, text_clean_fixed)

    if asset_no == '未识别到编号':
        asset_no = extract_robust_asset(text_fixed, text_clean_fixed, r'资\s*产\s*编\s*号|Asset\s*No', r'资产编号|AssetNo', exclude_str=serial_no_str)
        if asset_no != '未识别到编号' and not inst_name:
            inst_name = lookup_inst(asset_no)

    if not inst_name:
        inst_name = extract_robust_inst_name(text_fixed, r'计\s*量\s*器\s*具\s*名\s*称|Name\s*of\s*Instrument')
        if inst_name == '未查找到':
            fb = re.search(r'计\s*量\s*器\s*具\s*名\s*称.{0,100}?(' + INST_PATTERN + r')', text_fixed, re.DOTALL)
            if fb:
                inst_name = fb.group(1).strip()
                if re.match(r'^(MAC|MAA|MRA|CNAS|Model|Type|Description|Information|Certificate)$', inst_name.replace(' ',''), re.IGNORECASE): inst_name = '未查找到'
            if inst_name == '未查找到':
                inst_name = find_value_by_keyword(text_fixed, r'计\s*量\s*器\s*具\s*名\s*称|Name\s*of\s*Instrument', INST_PATTERN, search_range=15, col_tolerance_right=100) or '未查找到'

    cal_date = extract_robust_date(text_clean_fixed, text_fixed, r'校准日期|检定日期|OperationDate|VerificationDate', r'校\s*准\s*日\s*期|检\s*定\s*日\s*期|Operation\s*Date|Verification\s*Date') or '未知校准'
    issue_date = extract_robust_date(text_clean_fixed, text_fixed, r'签发日期|IssueDate', r'签\s*发\s*日\s*期|Issue\s*Date') or '未知签发'

    return {'asset_no': asset_no, 'inst_name': inst_name, 'cal_date': cal_date, 'issue_date': issue_date, 'group': lookup_group(asset_no)}

def extract_ccic(text, text_clean):
    text_fixed = re.sub(r'\b(DAF|DAP)\b', ' ', text, flags=re.IGNORECASE)
    text_fixed = re.sub(r'NobJo|NnopbJo|NOPBJO', 'NDJ0', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'HO(\d+)', r'H0\1', text_fixed, flags=re.IGNORECASE)
    text_fixed = re.sub(r'WI(\d+)', r'WJ\1', text_fixed, flags=re.IGNORECASE)
    text_clean_fixed = text_fixed.replace(' ', '').replace('\n', '')

    serial_match = re.search(r'(?:出厂编号|Serial\s*No\.?)\s*[:：]?\s*([A-Za-z0-9\-/]{4,})', text_fixed, re.IGNORECASE)
    serial_no_str = serial_match.group(1) if serial_match else None

    asset_no, inst_name = auto_match_from_registry(text_fixed, text_clean_fixed)

    if asset_no == '未识别到编号':
        asset_no = extract_robust_asset(text_fixed, text_clean_fixed, r'管\s*理\s*编\s*号|管\s*理\s*号|Asset\s*No\.?', r'管理编号|管理号|AssetNo\.?', exclude_str=serial_no_str)
        if asset_no != '未识别到编号' and not inst_name:
            inst_name = lookup_inst(asset_no)

    if not inst_name:
        inst_name = extract_robust_inst_name(text_fixed, r'仪\s*器\s*名\s*称|Description')
        if inst_name == '未查找到':
            inst_name_match = find_value_by_keyword(text_fixed, r'仪\s*器\s*名\s*称|Description', INST_PATTERN, search_range=15, col_tolerance_right=150)
            if inst_name_match and not re.search(r'市|区|街道|路|楼|社区|MAC|MAA|MRA|CNAS|Information|Certificate', inst_name_match, re.IGNORECASE):
                inst_name = inst_name_match
            else:
                for match in re.finditer(r'(?:仪\s*器\s*名\s*称|Description).{0,150}?(' + INST_PATTERN + r')', text_fixed, re.IGNORECASE | re.DOTALL):
                    val = match.group(1).strip()
                    if val and not re.search(r'市|区|街道|路|楼|社区|型号规格|制造厂商|出厂编号|管理编号|联络信息|MAC|MAA|MRA|CNAS|Information|Certificate', val, re.IGNORECASE):
                        inst_name = val
                        break

    cal_date = extract_robust_date(text_clean_fixed, text_fixed, r'校准日期|检定日期|DateofCalibration', r'校\s*准\s*日\s*期|检\s*定\s*日\s*期|Date\s*of\s*Calibration') or '未知校准'

    return {'asset_no': asset_no, 'inst_name': inst_name, 'cal_date': cal_date, 'group': lookup_group(asset_no)}

# ==========================================
# 第五步：组装文件名
# ==========================================

def build_new_name(issuer, fields):
    if issuer == 'DN':
        parts = [fields['lab_name'], fields['asset_no'], fields['cal_date'], fields['issue_date'], fields['inst_name']]
    elif issuer == 'NEM':
        parts = [fields['serial_no'], fields['inst_name'], fields['cal_date'], fields['group']]
    else:
        parts = [fields['asset_no'], fields['inst_name'], fields['cal_date'], fields['group']]
    return '_'.join([sanitize_filename(p) for p in parts])

# ==========================================
# 第六步：批量扫描 + 建档归档主循环
# ==========================================

ISSUER_LABEL = {
    'DN':      '东莞帝恩',
    'DAF':     '深圳达丰',
    'NEM':     '广州中广测',
    'SMQ':     '深圳计量院',
    'CCIC':    '中检深圳',
    'UNKNOWN': '未识别机构',
}

ARCHIVE_BASE_DIR = '【归档完成】'
if not os.path.exists(ARCHIVE_BASE_DIR):
    os.makedirs(ARCHIVE_BASE_DIR)

print(f"\n开始文件雷达扫描 (当前版本: {VERSION})...\n")

pdf_files_to_process = []
ignored_count = 0

for root, dirs, files in os.walk('.'):
    if ARCHIVE_BASE_DIR in root:
        ignored_count += sum(1 for f in files if f.lower().endswith('.pdf'))
        continue
    for filename in files:
        if filename.lower().endswith('.pdf'):
            pdf_files_to_process.append(os.path.join(root, filename))

print(f"📡 雷达扫描完毕：在当前非归档文件夹中共发现 {len(pdf_files_to_process)} 个待处理的 PDF 证书！")
if ignored_count > 0:
    print(f"   （另外有 {ignored_count} 个 PDF 已经被安全存放于【归档完成】文件夹中，本次自动跳过）\n")

if len(pdf_files_to_process) == 0:
    print("🛑 运行结束：由于没有找到任何需要处理的 PDF 文件，程序停止。")
    import sys
    sys.exit()

print("=" * 70)
print("开始执行提取与重命名...")

for file_path in pdf_files_to_process:
    filename = os.path.basename(file_path)
    root = os.path.dirname(file_path)

    try:
        text = ""
        used_ocr = False

        # ⚠️ 【极速升级点】：换用 fitz (PyMuPDF) 读取，速度和内存表现大幅提升
        with fitz.open(file_path) as pdf:
            pages_to_scan = min(3, len(pdf))
            for i in range(pages_to_scan):
                page = pdf[i]
                page_text = page.get_text("text") or ''

                # --- 核心：智能识别是否为纯图扫描件，并激活 RapidOCR ---
                text_clean_page = page_text.replace(' ', '').replace('\n', '')
                if len(text_clean_page) < 50 and USE_OCR:
                    print(f"   🔍 检测到 [{filename}] 疑似纯图片扫描页，正在启动 RapidOCR...")
                    try:
                        # 渲染为高精度图像，传给 OCR
                        pix = page.get_pixmap(dpi=200)
                        img_bytes = pix.tobytes("png")
                        result, _ = ocr_engine(img_bytes)
                        if result:
                            ocr_text = '\n'.join([line[1] for line in result])
                            page_text += '\n' + ocr_text
                            used_ocr = True
                    except Exception as e:
                        print(f"   ⚠️  OCR 识别失败: {e}")

                text += page_text + '\n'

        text_clean = text.replace(' ', '')
        issuer = identify_issuer(text_clean)

        # 第一次基础判定 (全图乱码层检测)
        if (len(text_clean.strip()) < 50 or issuer == 'UNKNOWN') and USE_OCR and not used_ocr:
            print(f"   🔍 [{filename}] 疑似乱码层或纯图，触发强制 RapidOCR 引擎抢救...")
            text_ocr = ""
            try:
                with fitz.open(file_path) as pdf:
                    for i in range(min(2, len(pdf))):
                        page = pdf[i]
                        pix = page.get_pixmap(dpi=200)
                        img_bytes = pix.tobytes("png")
                        result, _ = ocr_engine(img_bytes)
                        if result:
                            text_ocr += '\n' + '\n'.join([line[1] for line in result])

                text = text_ocr
                text_clean = text.replace(' ', '')
                issuer = identify_issuer(text_clean)
                used_ocr = True
            except Exception as e:
                print(f"   ⚠️  OCR 识别失败: {e}")

        fields = {}
        if issuer != 'UNKNOWN':
            if issuer == 'DN': fields = extract_dn(text, text_clean)
            elif issuer == 'DAF': fields = extract_daf(text, text_clean)
            elif issuer == 'NEM': fields = extract_nem(text, text_clean)
            elif issuer == 'SMQ': fields = extract_smq(text, text_clean)
            elif issuer == 'CCIC': fields = extract_ccic(text, text_clean)

            # --- 核心：二次视觉抢救机制 ---
            if (fields.get('asset_no') == '未识别到编号' or fields.get('inst_name') == '未查找到') and USE_OCR and not used_ocr:
                print(f"   🚨 [{filename}] 提取信息严重缺失(检测到扫描仪隐藏乱码层)，启动二次终极视觉抢救...")
                text_ocr = ""
                try:
                    with fitz.open(file_path) as pdf:
                        for i in range(min(2, len(pdf))):
                            page = pdf[i]
                            pix = page.get_pixmap(dpi=200)
                            img_bytes = pix.tobytes("png")
                            result, _ = ocr_engine(img_bytes)
                            if result:
                                text_ocr += '\n' + '\n'.join([line[1] for line in result])

                    text = text_ocr
                    text_clean = text.replace(' ', '')
                    issuer = identify_issuer(text_clean)
                    used_ocr = True

                    if issuer != 'UNKNOWN':
                        if issuer == 'DN': fields = extract_dn(text, text_clean)
                        elif issuer == 'DAF': fields = extract_daf(text, text_clean)
                        elif issuer == 'NEM': fields = extract_nem(text, text_clean)
                        elif issuer == 'SMQ': fields = extract_smq(text, text_clean)
                        elif issuer == 'CCIC': fields = extract_ccic(text, text_clean)

                except Exception as e:
                    print(f"   ⚠️  二次 OCR 抢救失败: {e}")

        if issuer == 'UNKNOWN':
            print(f"⚠️  {VERSION} 未识别机构：{filename}，跳过处理。")
            continue

        label = ISSUER_LABEL[issuer]

        new_stem = build_new_name(issuer, fields)
        new_name = f"{new_stem}.pdf"

        cal_date = fields.get('cal_date', '未知校准')
        if len(cal_date) == 8 and cal_date.isdigit():
            year_month = f"{cal_date[:4]}年{cal_date[4:6]}月"
        else:
            year_month = "未知年月"

        if issuer == 'DN':
            lab_name = sanitize_filename(fields.get('lab_name', '未知实验室'))
            folder_group = lab_name if lab_name.endswith('项目组') else lab_name.replace('组', '') + '项目组'
            target_folder_name = f"{year_month}{folder_group}校准证书"
        else:
            grp = sanitize_filename(fields.get('group', '未知组别'))
            target_folder_name = f"{year_month}{grp}校准证书"

        target_dir = os.path.join(ARCHIVE_BASE_DIR, target_folder_name)
        os.makedirs(target_dir, exist_ok=True)

        new_path = os.path.join(target_dir, new_name)
        counter = 1
        while os.path.exists(new_path) and os.path.abspath(new_path) != os.path.abspath(file_path):
            new_name = f"{new_stem}_{counter}.pdf"
            new_path = os.path.join(target_dir, new_name)
            counter += 1

        shutil.move(file_path, new_path)
        print(f"✅ [{label}] {filename}")
        print(f"   → 已归档至：{ARCHIVE_BASE_DIR}/{target_folder_name}/{new_name}")

        record = {
            '所在文件夹': target_folder_name,
            '原始文件名': filename,
            '最终重命名': new_name,
            '机构':     label,
            '编号':     fields.get('asset_no') or fields.get('serial_no', '—'),
            '仪器名称': fields.get('inst_name', '未查找到'),
            '校准日期': f"\t{fields.get('cal_date', '未知校准')}",
            '所属组别': fields.get('group') if issuer != 'DN' else folder_group,
            '备注':     f"签发/实验室: {fields.get('issue_date', '')} {fields.get('lab_name', '')}".strip()
        }
        extracted_info_list.append(record)

    except Exception as e:
        print(f"❌ 处理 [{filename}] 时发生错误：{e}")

# ==========================================
# 第七步：输出汇总清单
# ==========================================
if extracted_info_list:
    print("\n" + "=" * 70)
    print("正在生成汇总清单...")
    df_result = pd.DataFrame(extracted_info_list)
    col_order = ['所在文件夹', '原始文件名', '最终重命名', '机构', '编号', '仪器名称', '校准日期', '所属组别', '备注']
    df_result = df_result.reindex(columns=col_order)
    output_excel = f'本次扫描_校准信息归档汇总表_{VERSION}.xlsx'
    df_result.to_excel(output_excel, index=False, engine='openpyxl')
    print(f"\n🎉 全部处理完成！共处理 {len(extracted_info_list)} 份证书。")
    print(f"📂 所有证书已分类存入【{ARCHIVE_BASE_DIR}】文件夹中。")
    print(f"📋 汇总清单已保存至：【{output_excel}】")